# Generated by Django 5.0.7 on 2024-12-05 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('upload_file', models.FileField(upload_to='uploads/')),
                ('original_text', models.TextField(blank=True, null=True)),
                ('processed_data', models.TextField(blank=True, null=True)),
                ('p_status', models.CharField(blank=True, max_length=20, null=True)),
                ('data_type', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', '관리자'), ('user', '일반 사용자')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('u_status', models.CharField(choices=[('active', '활성'), ('suspended', '정지')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_content', models.TextField()),
                ('modified_content', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'server_filehistory',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PseudonymizedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym_id', models.CharField(max_length=50, unique=True)),
                ('pseudo_text', models.TextField()),
                ('processed_data', models.DateTimeField()),
                ('p_status', models.CharField(max_length=20)),
                ('upload_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.originaldata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.user')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('anonymized_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=50, unique=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_info', models.TextField()),
                ('login_status', models.CharField(choices=[('success', '성공'), ('failure', '실패')], max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.user')),
            ],
        ),
        migrations.CreateModel(
            name='GPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.CharField(max_length=50, unique=True)),
                ('input_text', models.TextField()),
                ('response_text', models.TextField()),
                ('upload_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.originaldata')),
                ('pseudonym_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.pseudonymizeddata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(max_length=50, unique=True)),
                ('access_type', models.CharField(max_length=50)),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('log_status', models.CharField(choices=[('success', '성공'), ('failure', '실패')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.user')),
            ],
        ),
    ]
